function figure1 = createIRfigure2(cdata1, X1, Y1, X2, Y2, X3, X4, X5, cdata2, cmap, datalimits)
%CREATEFIGURE(CDATA1, X1, Y1, X2, Y2, X3, X4, X5, CDATA2, cmap, datalimits)
%  CDATA1:  image cdata
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  X4:  vector of x data
%  X5:  vector of x data
%  CDATA2:  image cdata

%  Auto-generated by MATLAB on 16-Nov-2015 11:40:39

% Create figure
figure1 = figure('Colormap',cmap);
% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.132793296089386 0.48 0.776890133600439 0.4]);
hold(axes1,'on');
p0 = get(axes1,'pos'); %get axes position to reset after adding colorbar
colormap(cmap)

% Create image
image([-40.9819878472222 58.2682291666667],...
    [-56.5494791666667 62.7083333333333],cdata1,'Parent',axes1,...
    'CDataMapping','scaled'); %add image

cb = colorbar; %add color bar (changes axes position)
set (cb,'pos', [0.92 0.08 0.02 0.8], 'TickLabels',[datalimits(1):(datalimits(2)/10):datalimits(1)+datalimits(2)]) %move colorbar
set(axes1,'pos',p0)% reset axes position

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',axes1,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y2,'Parent',axes1,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X4,Y2,'Parent',axes1,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X5,Y2,'Parent',axes1,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create xlabel
xlabel('r [mm]');

% Create ylabel
ylabel('z [mm]');

%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 50]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 15]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'Layer','top','XAxisLocation','top');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.132793296089386 0.08 0.776890133600439 0.4]);
hold(axes2,'on');

% Create image
image([0 100],...
    [-15 15],cdata2,'Parent',axes2,...
    'CDataMapping','scaled');
colormap(cmap)
% Create plot
plot(X1,Y1,'Parent',axes2,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X2,Y2,'Parent',axes2,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X3,Y2,'Parent',axes2,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X4,Y2,'Parent',axes2,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

% Create plot
plot(X5,Y2,'Parent',axes2,'LineWidth',2,'LineStyle','--','Color',[0 0 0]);

%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes2,[0 50]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[0 15]);
ylabel('z [mm]');
box(axes2,'on');
set(axes2,'Layer','top')
axis(axes2,'ij');

% Set the remaining axes properties


